---
# hosts tasks
- name: Add all inventory hosts to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"
