---

- name: Provision a Jenkins CI server
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes

  roles:
    - base
#    - certbot
    - jenkins
    - nginx
